<?php

/**
 * @file
 * Provides a honor entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function mbgna_honor_theme() {
  return [
    'honor' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for honor templates.
 *
 * Default template: honor.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the honor information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_honor(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

